version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env.production
    volumes:
      - app_logs:/app/logs
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/financial_documents
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secure_password}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data:
  app_logs: