version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/financial_documents

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
