version: '3.8'
services:
  app:
    build: .
    ports:
      - "10000:10000"  # שיניתי ל-10000 לפי ה-PORT שמוגדר ב-Dockerfile שלך
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/financial_documents  # שינוי חשוב - שימוש בשם השירות במקום localhost
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # הסרתי את האימות כרגע כדי לפשט את הפתרון
    # אם תרצה להפעיל עם אימות, תצטרך לעדכן גם את MONGO_URI בהתאם

volumes:
  mongodb_data:
