version: '3.8'
services:
  app:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PORT=10000
      - USE_DYNAMODB=true
      - DYNAMODB_REGION=${AWS_REGION}
      - DEFAULT_LANGUAGE=he
      - SECRET_KEY=28
      - JWT_SECRET=210
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - SERVICE_NAME=${SERVICE_NAME}
      - LLM_PROVIDER=huggingface
