version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:10000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/financial_documents
      - LLM_PROVIDER=huggingface
  
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
