services:
  # A Python web service
  - type: web
    name: financial-doc-analyzer
    runtime: docker
    region: eu-west-1  # Choose an appropriate region
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_LANGUAGE
        value: he
      - key: HUGGINGFACE_API_KEY
        sync: false
        
databases:
  - name: financial-doc-mongodb
    plan: free
    region: eu-west-1
    ipAllowList: [] # only allow internal connections
