branch-defaults:
  master:
    environment: financial-docs-env
    group_suffix: null

global:
  application_name: financial-docs
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
