# This workflow is deprecated, please use deploy-to-lightsail-dynamo.yml instead
name: Deploy to AWS Lightsail (Deprecated)

# Disable this workflow by not having any triggers
on:
  workflow_dispatch:  # Only manual triggers, for emergency use

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show deprecation notice
        run: |
          echo "This workflow is deprecated."
          echo "Please use the 'Deploy to AWS Lightsail with DynamoDB' workflow instead."
          echo "See GITHUB_DEPLOYMENT.md for instructions."
          exit 1  # Fail the workflow to prevent accidental use
